# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ProductMailer`.
# Please instead update this file by running `bin/tapioca dsl ProductMailer`.


class ProductMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def in_stock; end
  end
end
